### PR TITLE
Ability to group validators error messages into one error message.

### PR DESCRIPTION
**Pull request by sebinsua**
I am not sure if this is the way we should do this.

In my code I have two checkboxes that both throw the same error message. If neither are selected then the error message should exist.

### CODE REVIEW

**Comment by lennym** [comment]
It's not 100% clear to me how this might be implemented. Can you provide an example?

**Comment by sebinsua** [comment]
This allows:

```javascript
    "should-contact-by-email": {
        "formatter": "boolean",
        "toggle": "enter-email",
        "validate": [
            { "type": "equal", "arguments": true, "group": "should-contact-by" }
        ],
        "dependent": {
            "field": "should-contact-by-text-message",
            "value": false
        }
    },
    "should-contact-by-text-message": {
        "formatter": "boolean",
        "toggle": "enter-mobile-number",
        "validate": [
            { "type": "equal", "arguments": true,"group": "should-contact-by" }
        ],
        "dependent": {
            "field": "should-contact-by-email",
            "value": false
        }
    }
```

The problem was that in LSR there is a group of checkboxes each with dependent text fields. If both checkboxes are unselected then it should show a *single* error message. If one or more checkboxes are selected then that error message should disappear.

There may well be a nicer way of doing this.

**Comment by lennym** [comment]
That makes sense I think. I'd just add some tests for it.

**Comment by sebinsua** [comment]
Okay.

**Comment by sebinsua** [comment]
The other closed PR actually had a 'not great' fix to a problem involving this + formatted fields that are dependent on each other. I'm going to try to fix in another commit.

Basically, if you are dependent on another field and when testing this dependency it does not pass, then the [default behaviour is to empty the value of the current field](https://github.com/UKHomeOffice/passports-form-controller/blob/master/lib/validation/index.js#L74). If there is yet another field that is dependent on this one, then it might be expecting a different kind of empty state. For example, you might have a checkbox that you have forced to be either `true` or `false` with a formatter, but now it is `''` the empty string causing other validations that have dependencies on this to not be executed.

What I'm going to do is to pass in the default empty state for a particular key (so that it can be `false` or `''` depending on how the formatters format an empty string).

**Comment by sebinsua** [comment]
@lennym

**Comment by lennym** [comment]
I think the empty state feels like unnecessary configuration. What's the use case for the dependency thing? 

If a field has not been interacted with then it will either post an empty string (or in some cases not exist on the body), but in either case this should be handled by the formatters, so the default empty state should just be the output of the configured formatters given either a body value of `''` or `undefined`.

**Comment by sebinsua** [comment]
@lennym A test of that behaviour.

**Pull request merged**
