### PR TITLE
closes #50 - support custom validators

### LINKED ISSUE #50: Allow custom validators
Custom validator functions passed in field config should be supported

### PR DESCRIPTION
**Pull request by joefitter**
* Allow end developer to supply a custom named validator for a field
* Accepts a named function, name is used to display validation error message

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @gavboulton @easternbloc @HughePaul @daniel-ac-martin - This PR allows custom validators to be passed through config rather than supplying a custom controller

**Comment by gavboulton** [comment]
LGTM

**Comment by joefitter** [comment]
@easternbloc @HughePaul @JoeChapman @daniel-ac-martin can I get another 👍  please?

**Comment by easternbloc** [comment]
🍑

**Comment by easternbloc** [comment]
@gavboulton LGTM can you merge plz

**Comment by gavboulton** [comment]
hmpo-form-controller@0.10.0 published.

**Pull request merged**
