### PR TITLE
Error redirection

### PR DESCRIPTION
**Pull request by gavboulton**
Only redirect users to error redirect if all errors have a redirect value. If there are other validation errors, let the user correct these first.

### CODE REVIEW

**Comment by lennym** [comment]
Does this leave a danger that some slightly odd looking error messages will be displayed for the fields that trigger redirects, but haven't redirected?

**Comment by gavboulton** [comment]
Error messages aren't displayed for field errors with redirects, but I don't know why.

**Comment by lennym** [comment]
https://github.com/UKHomeOffice/passports-form-wizard/blob/master/lib/controller.js#L27-L29

**Comment by lennym** [comment]
And having said that, I endorse this PR.

**Comment by lennym** [comment]
If you wanted to merge #27 then I can publish just the once.

**Pull request merged**
