### PR TITLE
Added a very concise explanation for the FormError class

### PR DESCRIPTION
**Pull request by barbaracassani**

### CODE REVIEW

**Comment by daniel-ac-martin** [comment]
LGTM.

**Comment by easternbloc** [comment]
@gavboulton fancy doing the release dance?

**Comment by gavboulton** [comment]
Can you make sure there's always agreement from an HMPO dev.

We've spoken to @barbaracassani about yesterday's PR and it's going to be revisited. `title` is much more related to a view and translation needs to be considered. The plan is to set the options passed into the constructor to the instance options.

**Comment by easternbloc** [comment]
@gavboulton ah sorry. @barbaracassani has been trying to get this merged for a few days and I think it was blocking her story so I was trying to speed things up for her.

**Pull request merged**
